Update arg parsing to clap v3
zerotier/zeronsd pull request #130
Opened 2022-02-03 21:45 UTC by tranzystorek-io

Updates argument parsing to the new version of clap, with its flagship `derive` feature that minimizes boilerplate code and automates type parsing.

Notable change: the verbosity flag seemed like a natural candidate for a `global`.

Also, by default clap 3 colors the help output, if that is unwanted it can be easily disabled.

2022-02-04 02:42 UTC, erikh commented
I'll take a peek at this later tonight. Thank you very much for the patch!

2022-02-07 04:24 UTC, erikh commented
Haven't forgotten about this, just waiting until monday :)

2022-02-07 20:56 UTC, erikh requested changes
Tentatively approving, aside from the outstanding comments. I still need to run tests (we don't have CI for this project yet).

For future patches, assuming you had a good experience and want to do more, please make sure you detail everything you changed. While appreciated (and arguably the right decision), the path/pathbuf stuff caught me by surprise and I'll need to take a deeper look at it with the tree merged.

2022-02-07 20:56 UTC, erikh commented on Cargo.toml
> +clap = { version = "3.0", features = ["derive"] }
Let's make this `^3` until it breaks. I think that'll be better for catching bugfixes and security efforts.

2022-02-07 20:56 UTC, erikh commented on src/main.rs
> +    // }
Please remove this line

2022-02-07 21:02 UTC, tranzystorek-io commented
Thanks for taking your time! I'll gladly apply the suggestions.

> For future patches, assuming you had a good experience and want to do more, please make sure you detail everything you changed.

That's a good point, if you have any other questions I'd be happy to answer them 😄

2022-02-07 21:04 UTC, erikh commented
Oh, no, I followed the patch, just not sure 100% how pathbuf in a few spots will affect the CLI usage of things, specifically around the options used less like authtoken. I just need to dink with it a little. No big deal, honest.

2022-02-08 03:41 UTC, erikh commented
Patches look good. I want to play with this, so give me through tomorrow and then barring any surprises I'll merge it. Thanks again.

2022-02-08 18:59 UTC, erikh commented
Ok, so the tests were failing to compile. I fixed that up and pushed it to your tree. Just figured it'd be simpler this way.

Thanks for the patch!

2022-02-08 18:59 UTC, merged